### PR TITLE
test(loading): add reproduction test for #1002

### PR DESCRIPTION
**Pull request by cric96**

### CODE REVIEW

**Comment by DanySK** [comment]
Uhmm... this is expected to fail, but it works already :open_mouth:

**Comment by cric96** [comment]
Ops, I think that giving the same name at two different PRs was not a good idea :smile: 

Indeed, looking at the actions results, you will see that this PR is failed:
https://github.com/AlchemistSimulator/Alchemist/actions/runs/1628357671
and the other is successful:
https://github.com/AlchemistSimulator/Alchemist/actions/runs/1628357686

**Comment by DanySK** [comment]
I think that we hit a bug in GitHub, the check suite tells me that tests are passing, but they are no. Anyway...

**Comment by DanySK** [comment]
The parallel PR has been merged into #1004

**Pull request closed without merging**
