### PR TITLE
style(alchemist-loader): unify cases in pattern matching at Simulation Model

### PR DESCRIPTION
**Pull request by cric96**

### CODE REVIEW

**Comment by DanySK** [comment]
Nice idea, but it cannot compile: they are two different extension methods, and extension methods are resolved statically.

(the JVM equivalent would be `int toInt(byte self)` and `int toInt(short self)`)

**Review by DanySK — CHANGES_REQUESTED** [review]

**Comment by cric96** [comment]
> Nice idea, but it cannot compile: they are two different extension methods, and extension methods are resolved statically.
> 
> (the JVM equivalent would be `int toInt(byte self)` and `int toInt(short self)`)

me

**Comment by DanySK** [comment]
`Type mismatch: inferred type is Any? but Int? was expected`

Dafuq, nice inference Kotlin compiler :laughing:

**Comment by DanySK** [comment]
Closing as Kotlin's type inferrer cannot generalize in this case.

**Pull request closed without merging**
