### PR TITLE
Fix SpecificPositions

### LINKED ISSUE #113: `SpecificPositions` bug
`SpecificPositions` is bugged as it calls `environment.makePosition()` with a single number.

Apparently, current impl

```
    private val positions: List<Position<*>> = positions.flatMap { it.map { environment.makePosition(it) } }
```
is not correct. A straightforward fix may be

```
    private val positions: List<Position<*>> = positions.map { environment.makePosition(*it.toList().toTypedArray()) }
```

### PR DESCRIPTION
**Pull request by fedpet**
Fixes #113

### CODE REVIEW

**Comment by fedpet** [comment]
> Super nice. Could you also document it in the wiki?

It's already documented [https://alchemistsimulator.github.io/latest/wiki/usage/yaml/](here)

By the way I'm having some issues at understanding why the build is failing

**Comment by DanySK** [comment]
Does it work on your system if you `./gradlew clean compileKotlin --parallel` ?

**Comment by fedpet** [comment]
> Does it work on your system if you `./gradlew clean compileKotlin --parallel` ?

yes it does

**Comment by DanySK** [comment]
Let's clean caches and re-run on CI, then.

**Comment by DanySK** [comment]
The failure seems reproducible.

**Comment by DanySK** [comment]
OK, there's actually a wrong test. Fixing.
(by the way, `compileTestKotlin` should fail on your machine as well)

**Comment by fedpet** [comment]
since I ran `gradle clean`, it hasn't failed anymore on my machine

**Comment by DanySK** [comment]
That's fixed, there's a ktlint rule ruining the party but it's overly pedantic and I'm suppressing it.

**Pull request merged**
