### PR TITLE
Refactoring + Support trait for scafi simulations

### PR DESCRIPTION
**Pull request by metaphori**
Adds a trait to capture recurrent queries to the simulator.
Plus, it does some refactoring, also to better guarantee consistency with sensor names.

### CODE REVIEW

**Comment by metaphori** [comment]
Wait @DanySK to merge it: I am considering releasing a new version of scafi,
which might impact this.

**Comment by DanySK** [comment]
It does not complete the build anyway

**Comment by metaphori** [comment]
Wait for ghost commits f53f33a - c7f0fb7 - 1f699f4 to be included in this PR, and corresponding Travis feedback

**Comment by DanySK** [comment]
@metaphori I'm going to ignore this PR until you give me a greenlight. Once I get it, I'll code review and consider merging.

**Pull request merged**
