### PR TITLE
Implement display for Environments that use GeoPositions

### PR DESCRIPTION
**Pull request by Vuksaa**

### CODE REVIEW

**Comment by DanySK** [comment]
@Vuksaa tell me when I should start the review. Also, we need to meet (virtually) so that you can show me the new UI

**Comment by Vuksaa** [comment]
@DanySK I'm available after around 19:30 during the week or at any time during the weekend. If that doesn't work for you, we can arrange for a specific time and date.

In the meantime, I'll merge develop into my branch.

**Comment by DanySK** [comment]
Nope, most definitely in the 10-18 range in a weekday. First let's solve the merge, then agree on a time slot.

**Comment by Vuksaa** [comment]
I remembered one very small refactoring change I wanted to make so I marked it as draft again

**Comment by DanySK** [comment]
OK, let me know when to run through it again

**Comment by Vuksaa** [comment]
I just want to rename a couple of methods in the `it.unibo.alchemist.input` package in alchemist-fxui, other than that I think you can keep reviewing the other stuff

**Comment by DanySK** [comment]
Yeah rename the package as well, stuff related to I/O goes into `it.unibo.alchemist.boundary`

**Pull request merged**
