### PR TITLE
docs(website): Add the Turin's stampede simulation showcase

### PR DESCRIPTION
**Pull request by kelvin-olaiya**

### CODE REVIEW

**Comment by kelvin-olaiya** [comment]
@DanySK, to have a repo with the working simulation, I've [forked](https://github.com/kelvin-olaiya/SanCarloSquareStampede) the alchemist-primer. Is that ok?

I still have to include the simulation video, but I'm not quite sure if adding it to the repo (+70MB) is reasonable.

**Review by DanySK — APPROVED** [review]

**Comment by DanySK** [comment]
We just need the video! Can you send it to me? You might be able to use the [GARR filesender](https://filesender.garr.it/)

**Comment by DanySK** [comment]
@kelvin-olaiya it is way better to use alchemist-primer as a template rather than as a fork, but anyway. Do not upload the video here, send it to me, I'll upload it to the Alchemist YT channel

**Comment by kelvin-olaiya** [comment]
Ah yes sorry, I actually used it as a template.

**Comment by DanySK** [comment]
Next steps:
1. @kelvin-olaiya send me the video
2. Upload on YT
3. embed in the page
4. merge

**Pull request merged**
