### PR TITLE
feat: add draw directed node effect

### PR DESCRIPTION
**Pull request by cric96**
Effect used in Macro Swarm paper: https://github.com/AggregateComputing/experiment-2023-coordination-swarm-behaviour

### CODE REVIEW

**Comment by DanySK** [comment]
@cric96 https://scans.gradle.com/s/nmmb343pwqku6/console-log?task=:alchemist-swingui:compileKotlin

**Comment by cric96** [comment]
> @cric96 https://scans.gradle.com/s/nmmb343pwqku6/console-log?task=:alchemist-swingui:compileKotlin

Do I need to add @file:Suppress("DEPRECATION") for the deprecation warning since the effect is deprecated, right? Also, I'm not very familiar with the Kotlin type system, so I was wondering if you have any tips on how to handle the unsafe cast situation. Your insights would be greatly appreciated! :))

**Comment by DanySK** [comment]
it's better to suppress for the class rather than for the entire file:

@Suppress("DEPRECATION")

**Comment by DanySK** [comment]
Type system wise, the Kotlin type system is in between Java and Scala (and closer to Java). No path-dependent types, no HKT, in this case you can't do much, you can suppress pointwise: `@Suppress("UNCHECKED_CAST")`.

I've sent you a commit with some changes to improve idiomaticity. Note: there are still style errors.

**Pull request merged**
